imageCredentials:
    registry: index.docker.io
    username: stxdocker1
    password: starlingX@01

smtp:
    host: smtp.ethereal.email
    port: 586
    username: username
    password: password

imap:
    host: imap.ethereal.email
    port: 993
    username: username
    password: password

numberReplicas:
    frontend: 4
    backend: 1
    debugger: 1
