# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  vm-executor:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    environment:
      shell: /bin/bash
      TERM: xterm
      TZ: "Europe/Berlin"

commands:
  setup-environment:
    description: "Setup test environment"
    steps:
      - run:
          name: Setup test environment
          command: |
            cd util
            sh setup-ubuntu18.04.sh
            npm install nodemailer
  deploy-oisp:
    description: "Deploy OISP"
    steps:
      - run:
          name: Deploy OISP
          command: "export PATH=$PATH:/snap/bin && make deploy-oisp-test"
  run-tests:
    description: "Run tests"
    steps:
      - run:
          name: Run tests
          command: "export PATH=$PATH:/snap/bin && make test"


jobs:
  e2e-test:
    executor: vm-executor
    steps:
      - checkout
      - setup-environment
      - deploy-oisp
      - run-tests

workflows:
  version: 2.1
  workflow:
    jobs:
      - e2e-test
