apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper:3.4.13
        name: zookeeper
        env:
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888"
        ports:
        - containerPort: 2181
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: zookeeper-data
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_zk"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
